//! EVSYS - Event System.
//!
//! DS40002413 section 16 "EVSYS - Event System", page 141.
//! https://ww1.microchip.com/downloads/aemDocuments/documents/MCU08/ProductDocuments/DataSheets/AVR32-16DD20-14-Complete-DataSheet-DS40002413.pdf#page=141
//!
//! Six routing channels connect a generator to one or more users with no CPU
//! in the loop. Wiring is two steps: point a channel at a generator with
//! `set_generator`, then subscribe a user with `connect`.
//!
//! Generator encodings are *per channel* -- which pins a channel can watch
//! differs (channels 0/1 see PORTA, 2/3 see PC1..3 + PD4..7, 4/5 see PF6/7)
//! and the encodings are not dense (PORTD on channels 2/3 starts at 0x4C).
//! Each channel is therefore typed against its own generated value group
//! (`EVSYS_CHANNELn`), which also carries the TCD0 sources the older
//! hand-written table omitted (`TCD0_CMPBCLR`, `TCD0_CMPASET`, `TCD0_CMPBSET`,
//! `TCD0_PROGEV` = 0xB0..0xB3 in every channel's ATDF value-group). Those four
//! encodings match DS40002413 / ATDF exactly; there is no separate TCD0_OVF
//! generator -- cycle/edge events are the compare and PROGEV pulses.

const std = @import("std");
const microzig = @import("microzig");
const gpio = @import("gpio.zig");

const chip = microzig.chip.peripherals;
const gen = microzig.chip.types.peripherals.EVSYS;

/// One of five independent event channels. Generators fan in,
/// users pick one channel each.
pub const Channel = enum(u3) {
    ch0 = 0,
    ch1 = 1,
    ch2 = 2,
    ch3 = 3,
    ch4 = 4,
    ch5 = 5,
};

/// The generated per-channel generator enum for `channel`: every legal ATDF
/// value for that specific channel.
pub fn Generator(comptime channel: Channel) type {
    return switch (channel) {
        .ch0 => @FieldType(@FieldType(gen, "CHANNEL0").underlying_type, "CHANNEL0"),
        .ch1 => @FieldType(@FieldType(gen, "CHANNEL1").underlying_type, "CHANNEL1"),
        .ch2 => @FieldType(@FieldType(gen, "CHANNEL2").underlying_type, "CHANNEL2"),
        .ch3 => @FieldType(@FieldType(gen, "CHANNEL3").underlying_type, "CHANNEL3"),
        .ch4 => @FieldType(@FieldType(gen, "CHANNEL4").underlying_type, "CHANNEL4"),
        .ch5 => @FieldType(@FieldType(gen, "CHANNEL5").underlying_type, "CHANNEL5"),
    };
}

/// Point a channel at a generator. The generator is typed against that
/// channel's own value group, so an encoding this channel does not support
/// fails to compile rather than silently doing nothing.
///
/// Example:
/// ```zig
/// evsys.set_generator(.ch0, .RTC_OVF);
/// evsys.set_generator(.ch2, .PORTD_PIN6);
/// ```
pub fn set_generator(comptime channel: Channel, generator: Generator(channel)) void {
    switch (channel) {
        .ch0 => chip.EVSYS.CHANNEL0.write(.{ .CHANNEL0 = generator }),
        .ch1 => chip.EVSYS.CHANNEL1.write(.{ .CHANNEL1 = generator }),
        .ch2 => chip.EVSYS.CHANNEL2.write(.{ .CHANNEL2 = generator }),
        .ch3 => chip.EVSYS.CHANNEL3.write(.{ .CHANNEL3 = generator }),
        .ch4 => chip.EVSYS.CHANNEL4.write(.{ .CHANNEL4 = generator }),
        .ch5 => chip.EVSYS.CHANNEL5.write(.{ .CHANNEL5 = generator }),
    }
}

/// Point a channel at an input pin.
///
/// Visibility comes from the datasheet's per-channel generator tables:
/// channels 0/1 watch PORTA pins, channels 2/3 watch PC1..PC3 and PD4..PD7,
/// channels 4/5 watch PF6/PF7. A pin the channel cannot see is a compile
/// error.
pub fn set_generator_pin(comptime channel: Channel, comptime pin: gpio.Pin) void {
    const G = Generator(channel);
    const name = "PORT" ++ switch (pin.port) {
        .a => "A_PIN",
        .c => "C_PIN",
        .d => "D_PIN",
        .f => "F_PIN",
    } ++ &[1]u8{@as(u8, '0') + pin.index};
    comptime {
        var ok = false;
        for (@typeInfo(G).@"enum".fields) |f| {
            if (std.mem.eql(u8, f.name, name)) ok = true;
        }
        if (!ok) {
            @compileError("EVSYS " ++ @tagName(channel) ++ " cannot be generated by " ++ name);
        }
    }
    set_generator(channel, @field(G, name));
}

/// An event user: a peripheral input a channel can drive.
///
/// DS40002413 section 16.5.3 "User n Channel Select", page 151: user
/// registers number channels from one, so zero means "not connected".
/// https://ww1.microchip.com/downloads/aemDocuments/documents/MCU08/ProductDocuments/DataSheets/AVR32-16DD20-14-Complete-DataSheet-DS40002413.pdf#page=151
pub const User = enum(u16) {
    ccl_lut0_a,
    ccl_lut0_b,
    ccl_lut1_a,
    ccl_lut1_b,
    ccl_lut2_a,
    ccl_lut2_b,
    ccl_lut3_a,
    ccl_lut3_b,
    adc0_start,
    /// Event output on PA2, or PA7 via `portmux.set_event_output_a`.
    event_out_a,
    /// Event output on PC2.
    event_out_c,
    /// Event output on PD7 via `portmux.set_event_output_d`.
    event_out_d,
    /// Event output on PF7, which is also the UPDI pin.
    event_out_f,
    usart0_irda,
    usart1_irda,
    tca0_count_a,
    tca0_count_b,
    tcb0_capture,
    tcb0_count,
    tcb1_capture,
    tcb1_count,
    tcd0_input_a,
    tcd0_input_b,

    fn reg(user: User) *volatile u8 {
        const E = chip.EVSYS;
        return @ptrCast(switch (user) {
            .ccl_lut0_a => &E.USERCCLLUT0A.raw,
            .ccl_lut0_b => &E.USERCCLLUT0B.raw,
            .ccl_lut1_a => &E.USERCCLLUT1A.raw,
            .ccl_lut1_b => &E.USERCCLLUT1B.raw,
            .ccl_lut2_a => &E.USERCCLLUT2A.raw,
            .ccl_lut2_b => &E.USERCCLLUT2B.raw,
            .ccl_lut3_a => &E.USERCCLLUT3A.raw,
            .ccl_lut3_b => &E.USERCCLLUT3B.raw,
            .adc0_start => &E.USERADC0START.raw,
            .event_out_a => &E.USEREVSYSEVOUTA.raw,
            .event_out_c => &E.USEREVSYSEVOUTC.raw,
            .event_out_d => &E.USEREVSYSEVOUTD.raw,
            .event_out_f => &E.USEREVSYSEVOUTF.raw,
            .usart0_irda => &E.USERUSART0IRDA.raw,
            .usart1_irda => &E.USERUSART1IRDA.raw,
            .tca0_count_a => &E.USERTCA0CNTA.raw,
            .tca0_count_b => &E.USERTCA0CNTB.raw,
            .tcb0_capture => &E.USERTCB0CAPT.raw,
            .tcb0_count => &E.USERTCB0COUNT.raw,
            .tcb1_capture => &E.USERTCB1CAPT.raw,
            .tcb1_count => &E.USERTCB1COUNT.raw,
            .tcd0_input_a => &E.USERTCD0INPUTA.raw,
            .tcd0_input_b => &E.USERTCD0INPUTB.raw,
        });
    }
};

/// Subscribe a user to a channel.
///
/// User registers number channels from one, with zero meaning "not
/// connected", hence the +1 -- the +1 is the hardware's rule, not a choice.
pub fn connect(user: User, channel: Channel) void {
    user.reg().* = @backingInt(channel) + 1;
}

/// Detach a user from any channel (its USER register becomes 0).
pub fn disconnect(user: User) void {
    user.reg().* = 0;
}

/// Fire software event A on the channels named in `mask` (bit i = channel i).
pub fn trigger_software_a(mask: u8) void {
    chip.EVSYS.SWEVENTA.write_raw(mask);
}

/// Fire software event B.
///
/// NOTE: event software channel B carries only channels 8/9 in the family
/// schema, and this six-channel part bonds neither -- the write lands in the
/// register but can never reach a user. Prefer `trigger_software_a`.
pub fn trigger_software_b(mask: u8) void {
    chip.EVSYS.SWEVENTB.write_raw(mask);
}
